name: Build Ubuntu Server LTS Image

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Install QEMU and OVMF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils ovmf

      - name: Get latest LTS version and codename
        run: |
          curl -s https://changelogs.ubuntu.com/meta-release-lts -o meta-release-lts
          LATEST_VERSION=$(awk '/^Version:/ {version=$2 " " $3} END {print version}' meta-release-lts)
          LATEST_CODENAME=$(awk '/^Dist:/ {codename=$2} END {print codename}' meta-release-lts)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "LATEST_CODENAME=$LATEST_CODENAME" >> $GITHUB_ENV
          echo "VERSION_SHORT=$(echo "$LATEST_VERSION" | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Check if newer LTS available
        run: |
          if [ -z "${{ env.LATEST_VERSION }}" ] || [ -z "${{ env.LATEST_CODENAME }}" ]; then
            echo "Failed to parse LTS info."
            echo "BUILD=false" >> $GITHUB_ENV
          else
            if [ -f current_version.txt ]; then
              CURRENT_VERSION=$(cat current_version.txt)
            else
              CURRENT_VERSION="24.04 LTS"
            fi
            if [ "${{ env.LATEST_VERSION }}" != "$CURRENT_VERSION" ]; then
              echo "New LTS version detected: ${{ env.LATEST_VERSION }}"
              echo "BUILD=true" >> $GITHUB_ENV
            else
              echo "No new LTS version."
              echo "BUILD=false" >> $GITHUB_ENV
            fi
          fi

      - name: Get latest ISO details for the LTS
        if: env.BUILD == 'true'
        run: |
          SHA256SUMS=$(curl -s https://releases.ubuntu.com/${{ env.LATEST_CODENAME }}/SHA256SUMS)
          ISO_NAME=$(echo "$SHA256SUMS" | grep 'live-server-amd64\.iso' | awk '{print $2}' | tr -d '*')
          ISO_CHECKSUM=$(echo "$SHA256SUMS" | grep 'live-server-amd64\.iso' | awk '{print $1}')
          ISO_URL="https://releases.ubuntu.com/${{ env.LATEST_CODENAME }}/$ISO_NAME"
          echo "ISO_URL=$ISO_URL" >> $GITHUB_ENV
          echo "ISO_CHECKSUM=sha256:$ISO_CHECKSUM" >> $GITHUB_ENV

      - name: Setup Packer
        if: env.BUILD == 'true'
        uses: hashicorp/setup-packer@v3.1.0

      - name: Packer init
        if: env.BUILD == 'true'
        run: packer init packer/ubuntu.pkr.hcl

      - name: Install QEMU plugin (fallback)
        if: env.BUILD == 'true'
        run: packer plugins install github.com/hashicorp/qemu

      - name: Packer build
        if: env.BUILD == 'true'
        run: |
          packer build \
            -var "iso_url=${{ env.ISO_URL }}" \
            -var "iso_checksum=${{ env.ISO_CHECKSUM }}" \
            -var "version_short=${{ env.VERSION_SHORT }}" \
            packer/ubuntu.pkr.hcl

      - name: Upload image as artifact
        if: env.BUILD == 'true'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ubuntu-${{ env.VERSION_SHORT }}-x86_64-v3.qcow2
          path: output/ubuntu-${{ env.VERSION_SHORT }}-x86_64-v3.qcow2
          retention-days: 90

      - name: Update tracked LTS version
        if: env.BUILD == 'true'
        run: |
          echo "${{ env.LATEST_VERSION }}" > current_version.txt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add current_version.txt
          git commit -m "Update to new LTS version ${{ env.LATEST_VERSION }}"
          git push
